version: '3.8'

services:
  app:
    build: ./app
    volumes:
      - ./secrets/kafka.pem:/run/secrets/kafka.pem:ro
      - ./secrets/sample.pem:/run/secrets/sample.pem:ro
      

    ports:
      - "5000:5000"

  
